In [1]:
import numpy as np

In [2]:
new_list=[1,6,5,4,9]

In [3]:
squaredlist=[]
for a in new_list:
    squaredlist.append(a*a)
squaredlist

[1, 36, 25, 16, 81]

In [4]:
arr=np.array(new_list)
np.square(arr)

array([ 1, 36, 25, 16, 81], dtype=int32)

In [5]:
arr+1

array([ 2,  7,  6,  5, 10])

In [6]:
np.sum(arr)

25

In [7]:
arr1=np.array([1,1,1,1,1])
arr*2

array([ 2, 12, 10,  8, 18])

In [8]:
#np.mean=calc mean
#np.std=calc standar deviation
#np.exp=exponetial of each element
#np.pow=raise each element to some power
#np.multiply/divide

In [9]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.random.randint(0,100,(10,10))

array([[38, 28, 43, 29, 23, 48, 53, 54,  8, 22],
       [27, 40, 34, 61, 88, 11, 74, 44, 45, 65],
       [72,  3, 82, 57,  5, 90, 98, 62, 27, 71],
       [24, 43,  4,  2, 84, 33,  2,  5, 61, 26],
       [86, 18, 80, 67,  4, 51, 14, 21, 76, 93],
       [93, 13, 38, 99, 35, 32, 13, 66, 32,  4],
       [81,  6, 47, 73, 36, 91, 45, 84, 56, 51],
       [21, 70, 83,  8,  1, 73, 47, 86, 63, 92],
       [53, 11, 83, 94, 97, 19, 13, 26, 25, 50],
       [45,  9, 15, 25, 18, 74, 51, 26,  5, 24]])

In [13]:
arr4=np.random.random((10,10))

In [14]:
arr4*2-1

array([[-0.37884849,  0.87062838, -0.53150774,  0.3903872 ,  0.39156959,
         0.79088979, -0.97919209,  0.10822755,  0.90824237, -0.22787872],
       [ 0.29596227,  0.13656261,  0.04406006,  0.31015112, -0.18101026,
        -0.94280386,  0.16785656,  0.62616362, -0.58646803, -0.09801857],
       [ 0.15602802, -0.79426185, -0.49052129,  0.67066023, -0.85400615,
         0.3304035 ,  0.10412171,  0.84556386,  0.15047813,  0.83288359],
       [-0.69309304,  0.80331057, -0.57627329, -0.93318407, -0.42418705,
        -0.59390136,  0.311276  ,  0.44537416,  0.57784805,  0.78719719],
       [-0.75099672, -0.67111904, -0.49540033,  0.93698981, -0.05932835,
         0.87345014,  0.06710338, -0.21069378,  0.43476292, -0.09595125],
       [ 0.15490649, -0.79517615,  0.86586481,  0.6836388 ,  0.19567778,
         0.29742517,  0.70744365,  0.89003058,  0.51519428,  0.08973185],
       [ 0.57372742,  0.5560062 ,  0.15879244,  0.59787639,  0.692444  ,
        -0.97118247,  0.72412456, -0.88264901

In [15]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [16]:
np.logspace(-4,4,9)

array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03,
       1.e+04])

In [17]:
a=np.random.randint(0,10,9)
a

array([6, 1, 0, 8, 3, 4, 5, 3, 4])

In [18]:
b=a.reshape(3,-1)
b

array([[6, 1, 0],
       [8, 3, 4],
       [5, 3, 4]])

In [19]:
a.shape,b.shape

((9,), (3, 3))

In [20]:
c=a.reshape(1,-1)
c

array([[6, 1, 0, 8, 3, 4, 5, 3, 4]])

In [21]:
c.shape

(1, 9)

In [22]:
np.max(c)

8

In [23]:
np.max(a)

8

In [24]:
np.argmax(c)
#gives index of max

3

In [25]:
np.argmax(a)

3

In [26]:
np.argmax(b, axis=1)

array([0, 0, 0], dtype=int64)

In [27]:
b[1:3,:2]

array([[8, 3],
       [5, 3]])

In [28]:
"HW"

'HW'

In [32]:
r=np.random.random((6,6))
s=r+1
s

array([[1.93032777, 1.0652418 , 1.7621841 , 1.42375045, 1.24701452,
        1.91054847],
       [1.47491587, 1.00498396, 1.42109899, 1.9813099 , 1.15153904,
        1.87038056],
       [1.50178021, 1.06495596, 1.71339533, 1.58290727, 1.4909098 ,
        1.09182949],
       [1.58377353, 1.37129907, 1.46804769, 1.35023357, 1.5325422 ,
        1.60281553],
       [1.32241405, 1.03549454, 1.46263106, 1.57811768, 1.84391894,
        1.46881976],
       [1.20202648, 1.28670002, 1.10824459, 1.62658112, 1.74462085,
        1.94391941]])

In [37]:
for i in range(6):
    n=np.mean(s[i])
    y=np.max(s[i])
    print("Mean={} and max={}".format(n,y))

Mean=1.5565111832158796 and max=1.9303277707514042
Mean=1.4840380538614497 and max=1.9813099012321704
Mean=1.4076296763690122 and max=1.71339532822302
Mean=1.4847852640262278 and max=1.6028155309745298
Mean=1.4518993379351794 and max=1.843918942261129
Mean=1.4853487455711687 and max=1.9439194077326902


In [51]:
print(np.mean(s,axis=0))
np.max(s,axis=0)

[1.50253965 1.13811256 1.48926696 1.59048333 1.50175756 1.6480522 ]
[1.93032777 1.37129907 1.7621841  1.9813099  1.84391894 1.94391941]


In [56]:
print((s[s<1.5]))
np.sum(s[s<1.5])

[1.0652418  1.42375045 1.24701452 1.47491587 1.00498396 1.42109899
 1.15153904 1.06495596 1.4909098  1.09182949 1.37129907 1.46804769
 1.35023357 1.32241405 1.03549454 1.46263106 1.46881976 1.20202648
 1.28670002 1.10824459]


25.51215069537394