In [1]:
import numpy as np

In [2]:
new_list=[1,6,5,4,9]

In [5]:
squaredlist=[]
for a in new_list:
    squaredlist.append(a*a)
squaredlist

[1, 36, 25, 16, 81]

In [8]:
arr=np.array(new_list)
np.square(arr)

array([ 1, 36, 25, 16, 81], dtype=int32)

In [9]:
arr+1

array([ 2,  7,  6,  5, 10])

In [10]:
np.sum(arr)

25

In [19]:
arr1=np.array([1,1,1,1,1])
arr*2

array([ 2, 12, 10,  8, 18])

In [20]:
#np.mean=calc mean
#np.std=calc standar deviation
#np.exp=exponetial of each element
#np.pow=raise each element to some power
#np.multiply/divide

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.random.randint(0,100,(10,10))

TypeError: random() takes at most 1 positional argument (3 given)

In [60]:
arr4=np.random.random((10,10))

In [61]:
arr4*2-1

array([[-0.3001227 ,  0.054496  , -0.25285194, -0.18988972, -0.14798231,
        -0.36705685, -0.22750453,  0.16632149, -0.52779685, -0.01879963],
       [-0.83234136,  0.23877209, -0.19446133,  0.08623388,  0.82140605,
         0.38630765,  0.16114869, -0.27787337, -0.51936803,  0.4289058 ],
       [ 0.39004678,  0.53122039, -0.94812715,  0.74758737, -0.52208147,
        -0.1348023 , -0.42096532,  0.06833948, -0.99535564,  0.12055509],
       [ 0.46231756,  0.24057023, -0.2391314 ,  0.74889043,  0.05075922,
         0.4793995 , -0.33092803, -0.44808435,  0.69175253,  0.11546763],
       [ 0.85390324, -0.99622624,  0.22309753, -0.48843187, -0.44139823,
         0.87600046,  0.39827578, -0.65919186,  0.76338967, -0.80031993],
       [-0.40075295,  0.01605398,  0.46515054, -0.98652536,  0.07590031,
        -0.44642839, -0.41595524, -0.32129917, -0.11445947,  0.07265865],
       [-0.85662801, -0.15931929, -0.33578387,  0.81518469,  0.33831333,
         0.21858119, -0.54451617, -0.51252909

In [68]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [75]:
np.logspace(-4,4,9)

array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03,
       1.e+04])

In [77]:
a=np.random.randint(0,10,9)
a

array([1, 9, 8, 7, 2, 5, 8, 6, 3])

In [90]:
b=a.reshape(3,-1)
b

array([[1, 9, 8],
       [7, 2, 5],
       [8, 6, 3]])

In [83]:
a.shape,b.shape

((9,), (3, 3))

In [91]:
c=a.reshape(1,-1)
c

array([[1, 9, 8, 7, 2, 5, 8, 6, 3]])

In [85]:
c.shape

(9, 1)

In [92]:
np.max(c)

9

In [93]:
np.max(a)

9

In [94]:
np.argmax(c)
#gives index of max

1

In [95]:
np.argmax(a)

1

In [99]:
np.argmax(b, axis=1)

array([1, 0, 0], dtype=int64)